// A more complete description is at:
// https://github.com/acheong08/apple-corelocation-experiments/blob/main/pb/BSSIDApple.proto#L5

message WifiDevice {
	required string bssid = 1;
	message Location {
		optional int64 latitude = 1;
		optional int64 longitude = 2;
		optional int64 horizontal_accuracy = 3;
		optional int64 altitude = 5;
		optional int64 vertical_accuracy = 6;
	}
	optional Location location = 2;
}

message AppleWLoc {
	repeated WifiDevice wifi_devices = 2;
	optional int32 num_wifi_results = 4; // -1 to disable, default seems to be 400
	optional string APIName = 5;
}
