# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AppleWLoc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x41ppleWLoc.proto\"\xbe\x01\n\nWifiDevice\x12\r\n\x05\x62ssid\x18\x01 \x02(\t\x12&\n\x08location\x18\x02 \x01(\x0b\x32\x14.WifiDevice.Location\x1ay\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x03\x12\x11\n\tlongitude\x18\x02 \x01(\x03\x12\x1b\n\x13horizontal_accuracy\x18\x03 \x01(\x03\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x03\x12\x19\n\x11vertical_accuracy\x18\x06 \x01(\x03\"Y\n\tAppleWLoc\x12!\n\x0cwifi_devices\x18\x02 \x03(\x0b\x32\x0b.WifiDevice\x12\x18\n\x10num_wifi_results\x18\x04 \x01(\x05\x12\x0f\n\x07\x41PIName\x18\x05 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AppleWLoc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFIDEVICE._serialized_start=20
  _WIFIDEVICE._serialized_end=210
  _WIFIDEVICE_LOCATION._serialized_start=89
  _WIFIDEVICE_LOCATION._serialized_end=210
  _APPLEWLOC._serialized_start=212
  _APPLEWLOC._serialized_end=301
# @@protoc_insertion_point(module_scope)
